# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# 这个文件夹是纯净的，与 example 组织无关。
version: '2'

services:
  peer-base:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      # peer 连接本机的 docker 的守护进程，这样才能创建链码容器。
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # 用默认的网桥网络来启动链码容器。
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      #- CORE_LOGGING_LEVEL=ERROR
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    # opt 明明是 go 的库目录，为什么这这里变成了工作目录呢？
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # 在外部节点，也是这样启动 peer 进程的。启动了以后，进程内自带各种系统链码。
    command: peer node start
